
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  build:
    name: "uploads3"
    arch: "amd64,arm,arm64"
    system: "windows,android,linux"
    mod: "none"
    packSrc: "hack,resource,manifest"
    version: "v1.0.0"
    path: "./bin"
    extra: -trimpath -ldflags="-s -w"
    #    cgo: true
    dumpEnv: true
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        descriptionTag: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app